import React from "react";
import AcademicsTemplate from "../../components/Academics-template";

export default function Ce() {
  const sectionContent = {
    team: "The Division of Civil Engineering came into existence with the inception of the Cochin University College of Engineering Kuttanad (CUCEK). The division was named as the Division of Civil Engineering and General Science, initially. Separate divisions of Civil Engineering and General Science were established from the academic year 2005-2006. B.Tech course in Civil Engineering was initiated in the academic year 2003-2004. Highly dedicated and sincere faculty and hardworking bunch of students is the principal of the division throughout the years. The Survey Lab, Concrete Lab, Strength of Materials Lab, Environmental Lab, Geotechnical Engineering Lab (set-up in progress), Building Technology Lab (set-up in progress) and the Civil Engineering Workshop are the existing laboratories of the division. Procurement of furniture and equipment to the Geotechnical Lab, Transportation Lab, Non-destructive testing Lab, Structural Dynamics Lab and a Computational Lab are expected in the near future. Most of the student projects are aimed at improving the quality of human habitat of the locality through new construction techniques, soil stabilization techniques, typical building designs, design of pontoon bridges, waste water and solid waste management techniques, crack mitigation, earthquake resistant design for the locality, etc. Presently, the division offers B.Tech program in Civil Engineering (4 year under-graduate course) and PhD program under the Faculty of Engineering, CUSAT through the School of Engineering. The employment of the successful students is ensured through campus placement, every year.",
    vision: "To produce and impart values, knowledge and skills in various areas of Civil Engineering with a global perspective and to groom professionals with ethical values and excellence to meet the current and future challenges in nation building.",
    achievements: "The second rank in B.Tech Civil Engineering under the University (CUSAT) was secured by Smt. Indu P Varghese of 2003-2007 B.Tech Civil Engineering (B.Tech degree examination April 2007). Dr. Sunilkumar N, Associate Profeesor of the division secured Prof. N S Govinda Rao gold medal for the best PhD thesis in the year 2011-2012 from the Department of Civil Engineering, Indian Institute of Science, Bangalore. His thesis was titled, “Smooth finite element methods through reproducing kernel DMS-splines”. The 2011-2015 batch B.Tech students of the division have published their projects in the International Conference in Recent Advances in Civil Engineering (ICRACE ‘16), 2016. Adarsh C, et al wrote the paper titled, “Stabilization sub-soil under typical road pavements in Kuttanad using coir geo-textiles” and was presented in the conference by Agaja A B. Senjo Sebastian, et al wrote the paper titled, “Planning and design of a floating bridge across the river Pampa at Kavalam” and presented in the conference by Rabeenson Thomas. Sri. Pratyush Kumar of B.Tech Civil Engineering 2012-2016 batch was short-listed for selection for direct PhD in the Department of Civil Engineering, Indian Institute of Technology, Chennai in October 2015.He has been selected for M.Tech program in IIT Bombay, IIT Bhuvaneswar and IIT Patna and stands first in the waiting list in IIT Roorkee. The students of the division are the defending overall champions (2015-2016) of sports and arts festival of CUCEK. They have secured second place in the previous year (2014-2015). The V semester B.Tech Civil Engineering batch (2011 Admission) won the first place in the Athappookkalam (Flower Carpet) competition conducted along with the Onam festival celebrations in August-Sep 2013. The V semester B.Tech Civil Engineering batch (2013 Admission) repeated the same triumph in the competition held in Aug-Sep 2015.",
    association:"The Association of Civil Engineering students was established in the academic year 2012-2013. The Association was named as “Federation of Remarkable Civil Engineers (FORCE)” and was inaugurated by Sri. Vinayakumar, Executive Engineer, Water Authority on 21.01.2013. He delivered a talk on “Concrete mix design and ready-mix concrete”. The Association aims at conducting technical programs for the benefit of the students, faculty and other stake holders in the discipline of civil engineering. They include seminars, project presentation, model making, technical games and quizzes, delivering technical lectures to the contractors, masons, and the public, etc. Conducting technical visits to industries and construction sites and supporting academically weaker students in their studies by forming students’ study groups are also part of the duties of the association. The executive committee of FORCE consists of the following members: president, vice-president, secretary, joint-secretary, treasurer and five executive committee members. The functions of the association are controlled by a faculty advisor. The executive committee is re-elected from among the students of B.Tech civil engineering, every year on 21st January during the anniversary celebrations of the association. Sri. Senjo Sebastian (2011-2015 batch) and Sri. Lalkrishna (2012-2015 batch) are the former presidents and Sri. Earnest Antony Green (2013-2016 batch) is the present president of FORCE.",
    hod: "Our Head of Department, Dr. John Doe, is a renowned figure in the field of AI.",
  };

  return (
    <AcademicsTemplate
      image="https://cucek.cusat.ac.in/img/civil/10.jpg"
      branchName="Civil Engineering"
      subtitle="We are civil and we do engineering"
      sectionContent={sectionContent}
      hodPhoto={"https://cucek.cusat.ac.in/images/PIC%20&%20SIGN/CE/FACULTY%20PICS/01.jpg"}
      hodName={"Dr.Sunil Kumar N"}
      hodProfilePath={"/"}
    />
  );
}
